(function(){
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const say=(m,t='')=>typeof window.toast==='function'?window.toast(m,t):console.log(m);
  const icon=(name,cls='ui-icon')=>({
    arrow:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M13 6l6 6-6 6"/></svg>',
    play:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M10 8.8v6.4L15.5 12 10 8.8Z" class="ui-fill"/></svg>',
    upload:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 16V7m0 0 4 4m-4-4-4 4"/><path d="M6.4 16.6A4.5 4.5 0 0 1 7 7.7 6 6 0 0 1 18.5 10 3.9 3.9 0 0 1 18 17H7"/></svg>',
    magic:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M9 3l1.7 4.3L15 9l-4.3 1.7L9 15l-1.7-4.3L3 9l4.3-1.7L9 3Z" class="ui-fill"/><path d="M17 4l.8 2.2L20 7l-2.2.8L17 10l-.8-2.2L14 7l2.2-.8L17 4Zm1 9 1 2.7 2.7 1-2.7 1L18 20l-1-2.3-2.7-1 2.7-1L18 13Z" class="ui-fill"/></svg>',
    cutout:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="5" width="14" height="14" rx="2"/></svg>',
    white:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="5" width="16" height="14" rx="3"/><path d="M8 9h8M8 13h5"/></svg>',
    center:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1.6" class="ui-fill"/><path d="M12 3v4M12 17v4M3 12h4M17 12h4"/></svg>',
    shield:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3.5 18.5 6v6c0 4.8-3.1 7.5-6.5 9-3.4-1.5-6.5-4.2-6.5-9V6L12 3.5Z"/><path d="m8.8 12 2.1 2.2 4.6-5"/></svg>',
    download:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 4v10m0 0 4-4m-4 4-4-4"/><path d="M5 16v4h14v-4"/></svg>',
    refresh:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 12a8 8 0 0 1-13.7 5.6"/><path d="M4 12A8 8 0 0 1 17.7 6.4"/><path d="M17.5 3.5v3.2h-3.2M6.5 20.5v-3.2h3.2"/></svg>',
    dashboard:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h7v6H4V5Zm9 0h7v6h-7V5ZM4 13h7v6H4v-6Zm9 0h7v6h-7v-6Z"/></svg>',
    history:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12a8 8 0 1 0 2.3-5.7"/><path d="M4 5.5V10h4.5M12 8v4l3 2"/></svg>',
    credit:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8"/><path d="M12 7v10M9 10.2c0-1.4 1.3-2.2 3-2.2 1.4 0 2.6.5 3.2 1.4M15 13.8c0 1.4-1.3 2.2-3 2.2-1.6 0-3-.6-3.6-1.7"/></svg>',
    settings:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1a7 7 0 0 0-1.8-1L14.4 3h-4.8l-.3 3.1a7 7 0 0 0-1.8 1l-2.4-1-2 3.4 2 1.5a7 7 0 0 0 0 2l-2 1.5 2 3.4 2.4-1a7 7 0 0 0 1.8 1l.3 3.1h4.8l.3-3.1a7 7 0 0 0 1.8-1l2.4 1 2-3.4-2-1.5c.1-.3.1-.7.1-1Z"/></svg>',
    project:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6.5A2.5 2.5 0 0 1 6.5 4H10l2 2h5.5A2.5 2.5 0 0 1 20 8.5v8A2.5 2.5 0 0 1 17.5 19h-11A2.5 2.5 0 0 1 4 16.5v-10Z"/></svg>',
    plus:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>',
    minus:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14"/></svg>',
    expand:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M8 4H4v4M16 4h4v4M8 20H4v-4M16 20h4v-4"/><path d="M4 4l6 6M20 4l-6 6M4 20l6-6M20 20l-6-6"/></svg>',
    menu:'<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 7h14M5 12h14M5 17h14"/></svg>'
  }[name]||'');
  function iconify(el,name,pos='start'){if(!el||el.dataset.iconified)return;const text=el.textContent.trim();el.dataset.iconified='true';el.innerHTML=pos==='end'?`<span>${text}</span>${icon(name)}`:`${icon(name)}<span>${text}</span>`}
  function replaceIconBox(el,name){if(!el)return;el.innerHTML=icon(name,'ui-icon large-icon')}
  function css(){const s=document.createElement('style');s.textContent=`
    .ui-soon{opacity:.58;cursor:not-allowed}.ui-soon:after{content:'即将上线';float:right;font-size:11px;color:#8a97aa;font-weight:900}.ui-note{margin:12px 0 0;color:#8a97aa;font-size:13px;text-align:center;line-height:1.65}.ui-error{color:#f97316!important;font-weight:850}.ui-empty{position:absolute;inset:72px 24px 24px;border:1px dashed var(--line);border-radius:18px;background:#fbfdff;display:grid;place-items:center;text-align:center;color:var(--muted);padding:22px;line-height:1.65;z-index:2}.ui-empty b{display:block;color:var(--navy);margin-bottom:6px}.ui-mobile[hidden],.ui-report[hidden]{display:none!important}.ui-mobile{position:fixed;inset:0;background:rgba(11,23,54,.42);z-index:70;display:flex;justify-content:flex-end;backdrop-filter:blur(8px)}.ui-mobile-card{width:min(360px,92vw);height:100%;background:#fff;padding:22px;box-shadow:-18px 0 50px rgba(11,23,54,.18);display:flex;flex-direction:column;gap:16px}.ui-mobile-head{display:flex;justify-content:space-between;align-items:center}.ui-mobile-close{width:36px;height:36px;border:1px solid var(--line);border-radius:10px;background:#fff;font-size:22px}.ui-mobile-links{display:grid;gap:10px}.ui-mobile-links a,.ui-mobile-links button{height:44px;border:1px solid var(--line);border-radius:13px;background:#fff;color:#33415c;font-weight:900;text-align:left;padding:0 14px}.ui-mobile-links .primary-btn{border:0;color:#fff;text-align:center;justify-content:center}.ui-report{position:fixed;inset:0;background:rgba(11,23,54,.46);z-index:90;display:grid;place-items:center;padding:24px;backdrop-filter:blur(8px)}.ui-report-card{width:min(560px,100%);max-height:86vh;overflow:auto;background:#fff;border:1px solid var(--line);border-radius:22px;box-shadow:0 28px 80px rgba(11,23,54,.22);padding:24px}.ui-report-card h3{margin:0 0 10px}.ui-report-card p{margin:0;color:var(--text);line-height:1.7}.ui-report-card ul{margin:16px 0 0;padding-left:20px;color:#33415c;line-height:1.9}.showcase-img{display:block;width:100%;height:100%;object-fit:contain}.product-stage .showcase-img{padding:8px}.template-thumb .showcase-img{padding:8px}.compare-before .showcase-img,.compare-after .showcase-img,.demo-shot .showcase-img{object-fit:cover}.showcase-demo-product{width:86%!important;height:86%!important;border-radius:0!important;box-shadow:none!important;background:center/contain no-repeat var(--showcase-demo)!important}.showcase-demo-product:before,.showcase-demo-product:after{display:none!important}
    .ui-icon{width:18px;height:18px;display:inline-block;flex:0 0 auto;stroke:currentColor;fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.ui-icon .ui-fill{fill:currentColor;stroke:none}.ui-icon.large-icon{width:28px;height:28px}.primary-btn,.secondary-btn,.ghost-btn,.light-btn{gap:9px;position:relative;overflow:hidden}.primary-btn{background:linear-gradient(135deg,#2f6bff 0%,#0b5cff 48%,#063bd8 100%);box-shadow:0 14px 30px rgba(11,92,255,.22),inset 0 1px 0 rgba(255,255,255,.28)}.primary-btn:hover{transform:translateY(-1px);box-shadow:0 18px 38px rgba(11,92,255,.28),inset 0 1px 0 rgba(255,255,255,.32)}.primary-btn:before{content:'';position:absolute;inset:0;background:linear-gradient(110deg,transparent 0%,rgba(255,255,255,.18) 42%,transparent 62%);transform:translateX(-120%);transition:transform .5s ease}.primary-btn:hover:before{transform:translateX(120%)}.primary-btn span,.secondary-btn span,.ghost-btn span,.light-btn span{position:relative;z-index:1}.primary-btn .ui-icon{position:relative;z-index:1}.secondary-btn,.ghost-btn{box-shadow:0 10px 22px rgba(11,23,54,.05)}.secondary-btn:hover,.ghost-btn:hover{border-color:#9fb9ff;color:var(--blue);box-shadow:0 12px 28px rgba(11,92,255,.1)}.light-btn{box-shadow:0 12px 26px rgba(11,23,54,.1)}.generate-btn,.mobile-action .primary-btn{min-height:48px;border-radius:15px}.feature-icon{font-size:0}.feature-icon .ui-icon{width:28px;height:28px}.dropzone span.upload-icon{width:58px;height:58px;border-radius:18px;background:#fff;display:grid;place-items:center;box-shadow:0 12px 24px rgba(11,92,255,.12);margin-bottom:4px}.dropzone span.upload-icon .ui-icon{width:34px;height:34px}.sidebar nav a{display:flex;align-items:center;gap:10px}.sidebar nav a .ui-icon{width:18px;height:18px}.sidebar nav a.active .ui-icon{color:#fff}.canvas-tools button{font-size:0}.canvas-tools button .ui-icon{width:18px;height:18px}.dash-actions .avatar{width:42px;height:42px;border-radius:14px;background:linear-gradient(135deg,#eef4ff,#fff);border:1px solid var(--line);display:grid;place-items:center;font-size:0}.dash-actions .avatar:before{content:'';width:20px;height:20px;border-radius:50%;background:linear-gradient(135deg,var(--blue),var(--blue2));box-shadow:0 10px 18px rgba(11,92,255,.22)}
    @media(max-width:900px){.topbar .desktop-nav{display:none}.topbar .menu-btn{display:inline-grid}.ui-note{text-align:left}.history-item{grid-template-columns:52px 1fr}.history-meta{grid-column:2;align-items:flex-start;flex-direction:row;flex-wrap:wrap}.ui-empty{inset:70px 14px 18px}}
  `;document.head.appendChild(s)}
  const showcaseAssets={white:'/assets/showcase/hero-white-earbuds.svg',caseAfter:'/assets/showcase/case-after-skincare.svg',shopify:'/assets/showcase/template-shopify-bag.svg'};
  function showcaseImage(src,alt){const img=document.createElement('img');img.className='showcase-img';img.src=src;img.alt=alt;img.loading='lazy';img.onerror=()=>{if(img.src.indexOf(showcaseAssets.white)===-1)img.src=showcaseAssets.white};return img}
  function fill(el,src,alt,mode){if(!el)return;const keep=mode==='pass'&&el.querySelector('.pass-badge');el.innerHTML='';el.appendChild(showcaseImage(src,alt));if(keep){keep.textContent='✓ 检测通过';el.appendChild(keep)}else if(mode==='pass'){const b=document.createElement('span');b.className='pass-badge';b.textContent='✓ 检测通过';el.appendChild(b)}}
  function showcase(){const stages=$$('.process-step .product-stage');const hero=[showcaseAssets.white,showcaseAssets.white,showcaseAssets.white,showcaseAssets.white];stages.forEach((el,i)=>fill(el,hero[i]||showcaseAssets.white,['卖家原图','自动抠图','白底主图','合规检测通过'][i]||'商品图',i===3?'pass':''));fill($('.compare-before'),showcaseAssets.caseAfter,'普通卖家商品原图');fill($('.compare-after'),showcaseAssets.caseAfter,'AI 生成白底商品主图');fill($('.uploaded-preview .demo-shot'),showcaseAssets.caseAfter,'待上传商品图示例');const demo=$('#demoProduct');if(demo){demo.classList.add('showcase-demo-product');demo.style.setProperty('--showcase-demo',`url(${showcaseAssets.caseAfter})`)};const applyTemplates=()=>{$$('[data-template-card]').forEach(card=>{const id=card.dataset.templateCard;const thumb=$('.template-thumb',card);const src=id==='shopify-main'?showcaseAssets.shopify:id==='amazon-white-main'||id==='temu-white-main'||id==='transparent-png'||id==='soft-shadow-packshot'||id==='mobile-cover-4x5'?showcaseAssets.caseAfter:showcaseAssets.white;fill(thumb,src,card.querySelector('h3')?.textContent||'模板示例')})};applyTemplates();const lt=$('#landingTemplates');if(lt)new MutationObserver(applyTemplates).observe(lt,{childList:true,subtree:true})}
  function mobile(){const b=$('.menu-btn'); if(!b)return; b.removeAttribute('data-scroll'); b.setAttribute('aria-expanded','false'); b.innerHTML=icon('menu'); const p=document.createElement('div'); p.className='ui-mobile'; p.hidden=true; p.innerHTML=`<div class="ui-mobile-card" role="dialog" aria-modal="true" aria-label="移动端导航"><div class="ui-mobile-head"><b>ProductShot AI</b><button class="ui-mobile-close" type="button" aria-label="关闭菜单">×</button></div><div class="ui-mobile-links"><a href="#features">功能</a><a href="#templates">模板</a><a href="#pricing">定价</a><a href="#cases">案例</a><button type="button" data-ui-scroll="dashboard">进入工作台</button><button class="primary-btn" type="button" data-ui-scroll="dashboard">免费生成主图</button></div></div>`; document.body.appendChild(p); const open=()=>{p.hidden=false;b.setAttribute('aria-expanded','true');$('.ui-mobile-close',p)?.focus()}; const close=()=>{p.hidden=true;b.setAttribute('aria-expanded','false');b.focus()}; b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open()},true); p.addEventListener('click',e=>{if(e.target===p||e.target.closest('.ui-mobile-close'))close(); const t=e.target.closest('[data-ui-scroll]'); if(t){close();document.getElementById(t.dataset.uiScroll)?.scrollIntoView({behavior:'smooth'})} if(e.target.closest('a[href^="#"]'))close()}); document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!p.hidden)close()})}
  function labels(){const login=$$('.desktop-nav button').find(x=>x.textContent.trim()==='登录'); if(login)login.textContent='进入工作台'; const map={0:'dashboard',2:'historyList',3:'templates'}; $$('.sidebar nav a').forEach((a,i)=>{if(map[i]){a.href='#'+map[i];a.onclick=e=>{e.preventDefault();document.getElementById(map[i])?.scrollIntoView({behavior:'smooth',block:'start'})}}else{a.classList.add('ui-soon');a.setAttribute('aria-disabled','true');a.onclick=e=>{e.preventDefault();say('该模块还未上线，当前版本先聚焦上传、生成、合规检测和历史。','error')}}}); const pt=$('.plan-card b'), ps=$('.plan-card small'), cr=$('.dash-actions .credit'); if(pt)pt.innerHTML='内测版 <span>演示状态</span>'; if(ps)ps.textContent='套餐和积分接口待接入，当前不展示真实余额'; if(cr)cr.textContent='内测模式'; $$('.primary-btn').filter(x=>x.textContent.includes('升级套餐')).forEach(x=>{x.textContent='套餐即将上线';x.onclick=e=>{e.preventDefault();say('套餐、积分和支付功能还未接入，当前版本先开放图片生成工作流。','error')}}); const pg=$('#pricing .pricing-grid'); if(pg&&!$('.ui-note',$('#pricing'))){const n=document.createElement('p');n.className='ui-note';n.textContent='套餐价格为内测展示，支付、积分扣费和团队账号功能尚未接入。';pg.after(n)}}
  function enhanceButtons(){
    const textOf=el=>el?.textContent.trim()||'';
    $$('.hero-actions .primary-btn,.desktop-nav .primary-btn,.bottom-cta .light-btn,.ui-mobile-links .primary-btn').forEach(b=>iconify(b,'arrow','end'));
    $$('.hero-actions .secondary-btn').forEach(b=>iconify(b,'play','end'));
    $$('#generateBtn,#mobileGenerateBtn').forEach(b=>{b.innerHTML=icon('magic')+'<span>生成主图</span>';b.dataset.iconified='true'});
    $$('#downloadAllBtn').forEach(b=>iconify(b,'download'));
    $$('#refreshHistoryBtn,#refreshHistoryListBtn').forEach(b=>iconify(b,'refresh'));
    $$('#complianceCard .secondary-btn.full').forEach(b=>iconify(b,'shield'));
    $$('.feature-card').forEach(card=>{const title=textOf(card.querySelector('h3'));const box=card.querySelector('.feature-icon');if(title.includes('抠图'))replaceIconBox(box,'cutout');else if(title.includes('白底'))replaceIconBox(box,'white');else if(title.includes('居中'))replaceIconBox(box,'center');else if(title.includes('合规'))replaceIconBox(box,'shield')});
    const dz=$('.dropzone > span'); if(dz){dz.className='upload-icon';dz.innerHTML=icon('upload')}
    const navIcons=['magic','project','history','dashboard','credit','settings']; $$('.sidebar nav a').forEach((a,i)=>{if(a.dataset.navIconified)return;let label=textOf(a).replace(/^[↥□◷▦◎⚙]\s*/,'');a.dataset.navIconified='true';a.innerHTML=icon(navIcons[i]||'dashboard')+`<span>${label}</span>`});
    const tools=$$('.canvas-tools button'); if(tools[0])tools[0].innerHTML=icon('minus'); if(tools[1])tools[1].innerHTML=icon('plus'); if(tools[2])tools[2].innerHTML=icon('expand');
    const obsTargets=[$('#templateOptions'),$('#landingTemplates'),$('.result-toolbar'),$('#complianceCard')].filter(Boolean); obsTargets.forEach(target=>{if(target.dataset.uiButtonObserver)return;target.dataset.uiButtonObserver='true';new MutationObserver(()=>setTimeout(enhanceButtons,0)).observe(target,{childList:true,subtree:true})});
  }
  function clearEmpty(){$('.ui-empty')?.remove()} function empty(title,detail){const c=$('#previewCanvas'); if(!c)return; clearEmpty(); const img=$('#resultImage'), demo=$('#demoProduct'), badge=$('#generatedBadge'); if(img)img.hidden=true;if(demo)demo.hidden=true;if(badge){badge.textContent='待生成';badge.className='generated-badge'} const d=document.createElement('div'); d.className='ui-empty'; d.innerHTML=`<div><b>${title}</b><span>${detail}</span></div>`; c.appendChild(d)}
  function tabs(){const t=$('#previewTabs'); if(!t)return; t.addEventListener('click',e=>{const b=e.target.closest('button[data-tab]'); if(!b)return; if(b.dataset.tab!=='cutout'){clearEmpty();return} e.preventDefault();e.stopImmediatePropagation(); $$('#previewTabs button').forEach(x=>x.classList.toggle('active',x===b)); const card=$$('.result-card').find(x=>x.textContent.includes('透明 PNG')); const im=card?.querySelector('img'); if(im?.src&&typeof window.setPreviewImage==='function'){clearEmpty();window.setPreviewImage(im.src,'抠图预览');say('已切换到透明 PNG 抠图结果','success')}else empty('暂无抠图结果','生成完成后，这里会显示透明 PNG 抠图预览。')},true)}
  function tools(){const bs=$$('.canvas-tools button'), lab=$('.canvas-tools span'), c=$('#previewCanvas'); if(bs.length<4||!lab||!c)return; let z=1; const apply=()=>{const target=$('#resultImage:not([hidden])')||$('#demoProduct:not([hidden])'); if(target){target.style.transform=`scale(${z})`;target.style.transition='transform .18s ease'} lab.textContent=Math.round(z*100)+'%'}; bs[0].setAttribute('aria-label','缩小预览');bs[1].setAttribute('aria-label','放大预览');bs[2].setAttribute('aria-label','全屏预览');bs[0].onclick=()=>{z=Math.max(.5,z-.1);apply()};bs[1].onclick=()=>{z=Math.min(2,z+.1);apply()};bs[2].onclick=()=>c.requestFullscreen?c.requestFullscreen():say('当前浏览器不支持全屏预览。','error')}
  function report(){const b=$('#complianceCard .secondary-btn.full'); if(!b)return; b.textContent='查看合规摘要'; const m=document.createElement('div'); m.className='ui-report'; m.hidden=true; m.innerHTML=`<div class="ui-report-card" role="dialog" aria-modal="true" aria-label="合规检测摘要"><h3>合规检测摘要</h3><p class="ui-report-intro"></p><ul class="ui-report-list"></ul><div class="modal-actions"><button class="primary-btn" type="button" data-close-report>知道了</button></div></div>`; document.body.appendChild(m); const close=()=>{m.hidden=true;b.focus()}; b.onclick=e=>{e.preventDefault(); const score=$('#scoreText')?.textContent?.trim()||'--'; const rows=$$('#complianceList li').map(x=>x.textContent.trim()).filter(Boolean); if(!rows.length||rows.some(x=>x.includes('暂无')||x.includes('上传并生成'))){say('生成主图后才能查看合规摘要。','error');return} $('.ui-report-intro',m).textContent=`当前合规评分：${score} / 100。以下为本次检测项和需要确认的问题。`; $('.ui-report-list',m).innerHTML=rows.map(x=>`<li>${x}</li>`).join(''); m.hidden=false; $('[data-close-report]',m)?.focus()}; m.onclick=e=>{if(e.target===m||e.target.closest('[data-close-report]'))close()}; document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!m.hidden)close()})}
  function uploadState(){const s=$('#uploadStatus'); if(!s)return; const sync=()=>{const text=s.textContent||''; s.classList.toggle('ui-error',/失败|过大|损坏|不支持/.test(text)); if(/上传失败/.test(text)) $$('#generateBtn,#mobileGenerateBtn').forEach(b=>{b.disabled=true;b.title='图片尚未成功上传，请重新选择或重试上传'}); if(/上传完成/.test(text)) $$('#generateBtn,#mobileGenerateBtn').forEach(b=>{b.disabled=false;b.removeAttribute('title')})}; new MutationObserver(sync).observe(s,{childList:true,characterData:true,subtree:true}); sync()}
  document.addEventListener('DOMContentLoaded',()=>{css();showcase();mobile();labels();enhanceButtons();tabs();tools();report();enhanceButtons();uploadState()});
})();
